
services:
  - docker
language: python

env:
  - IMGTAG=debian10-python3
  - IMGTAG=fedora31-python3
  - IMGTAG=ubuntu18.04-python3
  - IMGTAG=ubuntu19.10-python3

before_install:
- docker pull exaile/exaile-testimg:${IMGTAG}

script:
- docker run --rm -it -e HOME=/home -v $(pwd):/app -w /app exaile/exaile-testimg:${IMGTAG} make BUILDDIR=/tmp test test_compile check-doc

jobs:
  include:
  - stage: format-check
    language: python
    python:
    - "3.6"
    install:
    - pip install black
    script:
    - make check_format
  - stage: deploy
    language: python
    python:
    - "3.6"
    if: tag IS present
    script:
    - make DIST_VERSION=$TRAVIS_TAG dist
    deploy:
      provider: releases
      draft: true
      api_key: $EXAILEBOT_OAUTH_KEY
      file_glob: true
      file: dist/*
      skip_cleanup: true
      on:
        branch: automation
        tags: true

notifications:
  irc:
    if: fork = false
    channels:
    - "chat.freenode.net#exaile"
    use_notice: false
    skip_join: false
    on_success: change
    template:
      - "%{repository_name} %{branch} | %{build_url} | %{compare_url} | %{message}"
